### ISSUE TITLE
How to use showOnlySummary in coverage-text ?

### ISSUE THREAD

**Issue by e-belair** [sebastianbergmann/php-code-coverage#1026]
I see this option [in the source code](https://github.com/sebastianbergmann/php-code-coverage/blob/d10b53a877ad06afe11afdd39a391cd86382827c/src/Report/Text.php#L54) but I don't know where I can enable it.

EDIT:
I tried :
- coverageTextShowOnlySummary in phpunit.xml
- --coverage-text-show-only-summary in cli arg

No luck :sob: 

php-code-civerage 10.1.11
PHPUnit 10.5.5
PHP 8.1.27 
PCOV 1.0.11

**Comment by JoolsMcFly** [comment]
A bit late to the game but since I was wondering the same today I thought I'd let you know.

The arg you have to pass is `--only-summary-for-coverage-text`.
[Source code](https://github.com/sebastianbergmann/phpunit/blob/d81cfde3082807ab0db366c8424cb5bbbfcdc03b/src/TextUI/Configuration/Cli/Builder.php#L358).

**Comment by e-belair** [comment]
I've tried it and it works, thank you !
