### ISSUE TITLE
Move parsing of annotations from PHP_CodeCoverage to PHPUnit

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#162]
To further decouple PHP_CodeCoverage from PHPUnit and to ease the implementation of #140, the parsing of the `@codeCoverageIgnore*` annotations should be moved from PHP_CodeCoverage to PHPUnit.

**Comment by EzhilGayathri** [comment]
Hi,
   I am using phpunit 4.7 version with codeigniter framework 1.x. Iam not sure CI exact version as Iam new to this php field. I want to test a method where I used @runInSeparateProcess annotation. Here the test runs without fail but am not getting HTML code coverage.


PHPUnit 4.7.0 by Sebastian Bergmann and contributors.
Warning:        No whitelist configured for code coverage

.

Time: 9.79 seconds, Memory: 19.75Mb

OK (1 test, 0 assertions)

Generating code coverage report in HTML format ... done

**Comment by sebastianbergmann** [comment]
@EzhilGayathri Please do not hijack existing issues for new topics. Also: PHPUnit 4.7 is not supported anymore.

**Comment by EzhilGayathri** [comment]
Since my application is  legacy code of past 6 years. I want to test phpcode, let me know is there any possibility to obtain codecoverage in html format for  a test program which uses @runInSeparateProcess annotation. Could you clarify this?.As I am new to PHP, few issues are faced where I don't know what it exactly means.
