### ISSUE TITLE
Division by Zero on crap4j.php 

### ISSUE THREAD

**Issue by sataris** [sebastianbergmann/php-code-coverage#298]
When generating crap4j coverage through PHPUnit, Crap4j.php returns a Division by Zero error (Not sure if this is something I've misconfigured or not)

    PHPUnit 4.3.0 by Sebastian Bergmann.

    Configuration read from /var/www/mcm/build/phpunit.xml

    ....

    Time: 37.54 seconds, Memory: 7.00Mb

    OK (4 tests, 4 assertions)

    Generating code coverage report in Clover XML format ... done

    Generating Crap4J report XML file ...PHP Warning:  Division by zero in phar:///usr/local/bin/phpunit/php-code-coverage/CodeCoverage/Report/Crap4j.php on line 132
    PHP Stack trace:
    PHP   1. {main}() /usr/local/bin/phpunit:0
    PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:604
    PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
    PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
    PHP   5. PHP_CodeCoverage_Report_Crap4j->process() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:451

**Comment by eidng8** [comment]
I'm still getting this error, with PHPUnit 4.4.1 from composer. I can see the 
https://github.com/sebastianbergmann/php-code-coverage/commit/7eb9b5f1299eef1c9bb70f8c2acd2386564bda13 is in place.

Back to [line](https://github.com/sebastianbergmann/php-code-coverage/blob/7eb9b5f1299eef1c9bb70f8c2acd2386564bda13/src/CodeCoverage/Report/Crap4j.php#L132) it seems the variable `$fullMethodCount` is 0. However it gets increment at [line 104](https://github.com/sebastianbergmann/php-code-coverage/blob/7eb9b5f1299eef1c9bb70f8c2acd2386564bda13/src/CodeCoverage/Report/Crap4j.php#L104) not wrapped in any conditional. So it seems the variable can only be 0 under the circumstance that either of the outer foreach is not run, which means no class or no method in class.

This happens to meet my case, since I'm testing a file with just functions in it. Am I drawing the correct assumption?

P.S.
I'm not sure if I should modify the logic/process of it, so I've just done a quick hack to my local file as follow:

```php
$stats->appendChild($document->createElement('crapMethodPercent', $this->roundValue($fullMethodCount > 0 ? 100 * $fullCrapMethodCount / $fullMethodCount : 0)));
```

**Comment by sebastianbergmann** [comment]
Please open a new ticket (and include a minimal, self-contained, reproducing test case) if this problem still exists in the current version of PHP_CodeCoverage.
