### ISSUE TITLE
Remove HHVM driver

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#324]
HHVM is supposed to implement code coverage functionality that is API compatible with Xdebug. If that is the case then we should remove the `PHP_CodeCoverage_Driver_HHVM` class.

**Comment by stof** [comment]
@sebastianbergmann Travis still provides HHVM 3.5 (because newer versions are not compatible with Ubuntu 12.04), which does not have the XDebug-compatible API. This makes it impossible to generate code coverage on HHVM on Travis.
Could the driver based on the legacy API be added again for old HHVM versions ?

**Comment by sebastianbergmann** [comment]
It could but I don't want to. I am so happy that with October's PHPUnit 5 release I won't have to support PHP 5.3, 5.4, and 5.5 anymore. I will be even happier when PHPUnit 6 drops support for PHP 5 in August 2016. Supporting multiple versions of HHVM would be just as bad. If somebody wants to use HHVM then they are "out of luck" when they are not on a current version.
