### ISSUE TITLE
The warning for no whitelist is displayed when it should not

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/php-code-coverage#347]
See https://travis-ci.org/Incenteev/IncenteevTranslationCheckerBundle/jobs/65867671 displaying ``Warning:	No whitelist configured for code coverage`` while the config contains it: https://github.com/Incenteev/IncenteevTranslationCheckerBundle/blob/a5be86105f118f843e5fd4d4cd76520f8da1db45/phpunit.xml.dist

**Comment by sebastianbergmann** [comment]
I can only reproduce this when Xdebug is not loaded.

**Comment by stof** [comment]
indeed. It was not showing it locally with XDebug loaded

**Comment by rnowosielski** [comment]
Can you say something more about it ? I am running into a similar issue, where I get a warning `Warning: No whitelist configured for code coverage` but the code coverage is generated properly for all classes. 

I do have xdebug loaded although I am not sure if I maybe I would need to so something more ?

**Comment by sebastianheise** [comment]
@rnowosielski  - Same here unfortunately. Must be another unrelated bug though...

**Comment by sebastianbergmann** [comment]
Are you saying that you have a whitelist configured but get the warning that you have not?

**Comment by sebastianheise** [comment]
Morning Sebastian,
I (thought I) had the whitelist configured, but I did get the warning anyway.

However, I just solved it a few minutes ago and it turns out to be a misconfiguration (of course).

Unfortunately phpunit is not very talkative (not even in debug mode) when it comes to configuration issues. 

For me it was an incorrect path definition. My configuration was lacking the trailing slashes in the "directory" directive. 
I incorrectly assumed that since the directive is called "directory" a simple value of "../module" would be sufficient. But it had to be "../module/" however.

**Comment by rnowosielski** [comment]
Thanks! It helped me - somehow I haven't thought of it.

**Comment by KorvinSzanto** [comment]
Oh Lord, this took me way too long. Thank you!

**Comment by lucidlogic** [comment]
+1 saved me pain and suffering

**Comment by bluesliverx** [comment]
+1, but mine was just an incorrect path.  It turns out it uses the path of the XML config file when you are doing the whitelist.  This should be documented or the logging improved :)

**Comment by flancer64** [comment]
it was an incorrect path in my case (relative to phpunit.dist.xml, not to shell script that runs tests).

**Comment by dancinmoonlit** [comment]
Incorrect path in my case too. Thanks didnt realize that would really cause an havoc
