### ISSUE TITLE
Add no-index no-follow to code-coverage report

### ISSUE THREAD

**Issue by expolit** [sebastianbergmann/php-code-coverage#407]
I think, if you try to google "Generated by PHP_CodeCoverage"  you can find a lot of private test-coverage reports which may contain private info such as configuration values, passwords. Just add a couple of keywords and minus phrases to the above query.

So, I think you should implement http://www.robotstxt.org/meta.html and http://www.robotstxt.org/faq/relnofollow.html to close it from indexing. 

What do you think?

**Comment by MajorCaiger** [comment]
If this information is truly private and you don't want it to be found, then it shouldn't be in your web root. Even if robots don't find it, what's stopping humans trying to guess where your coverage report might be?

**Comment by expolit** [comment]
You know, there is a lot of idiots in the world. Someone still forgot to close directory index on .svn or .git directories. The job of software developer is to make it harder to shot yourself in the leg :)

So I think this is a really useful feature

**Comment by MajorCaiger** [comment]
I was amazed (I think) to see how many results I got when googling. I can't understand why anybody would leave their coverage report in the web root for the world to see. Even though I didn't spot any passwords, you can still find vulnerabilities in their code (or potentially steal their code) etc. Part of me thinks, for what it's worth it could be easily added in, but another part of me thinks it's still not removing the reports, it's just making them harder to find, and is that the responsibility of php-code-coverage?

**Comment by krakjoe** [comment]
Malicious software, of the kind that scans the interweb for passwords or whatever, doesn't care about bot rules ... so ... this isn't really a solution to the problem.

As mentioned, don't put it in your webroot ...

**Comment by expolit** [comment]
Yes, It will not protect from spiders, but It much harder to scan every website, than just make a query to google.

**Comment by krakjoe** [comment]
In doing anything at all, you're saying "we got this" ... in a sense, it's a green light for people to carry on putting sensitive information in their webroots because "we got this" ... I think it better to make a big deal out of it, and educate people so that they don't make that mistake ... 

If the best you can do for someone with a severed jugular vein is put a plaster on it, you're not really helping that person ...

**Comment by sebastianbergmann** [comment]
I agree with @krakjoe.

**Comment by expolit** [comment]
It's like 5 lines of code. Are you sure that you want to close it?

**Comment by dbr-foodpanda** [comment]
I agree with @expolit. This is nothing like giving a green light. Nobody will look at the coverage report source and will say, "hey, no-follow. I'm good to go. I can leave it in my public folder" or google for the coverage report to see if it shows up. Nothing is stopping you from addressing it in the docs and advocating for a secure solution. This is just a minimal effort to at least not make it worse by publicly spreading this potentially dangerous information on search engines. This is pretty much a zero effort, zero complications change that can be done alongside whatever plans you have in mind instead.

**Comment by MajorCaiger** [comment]
I think if you are stupid enough to leave the coverage report in the web-root, then you should face the repercussions. Whether robots find them or not isn't going to make any difference. You are basically making your source code public to the world. I am surprised that developers who bother to unit test their code, don't know better.

**Comment by dbr-foodpanda** [comment]
Yes, welcome to the real world. People make mistakes, they use tools without fully understanding them and they don't take security serious sometimes. Remember when aws-credentials were (are?) searchable on github, or when mongodb- or elasticsearch-instances were reachable via internet because people didn't read the docs and bother to secure them? It happens. It's not necessarily stupidity, in most cases it's just carelessness. You can't prevent all those cases, but if there is a low cost way for projects to make it less terrible, I think it's their responsibility to do so.

**Comment by MajorCaiger** [comment]
But no-index no-follow does not solve this problem. It applies a little paint over the cracks, but if someone wants to find it, they will still find it.

**Comment by dbr-foodpanda** [comment]
Yes, that was already established and I never said it will solve the issue. I just said "make it less terrible" and this might be considered as "sweeping it under the carpet". If it helps don't view these changes in light of the greater security-aspect discussed, but rather as a change to not make those reports searchable via search engines. There is no requirement to make them accessible via search engines, so just don't make them accessible. This is not bad even if you don't worry that it might expose sensitive information. The actual security issue can be addressed by different means, e.g. adding a warning to the docs.

**Comment by krakjoe** [comment]
> You can't prevent all those cases, but if there is a low cost way for projects to make it less terrible, I think **it's their responsibility to do so**.

Let's put aside the argument that this makes it less terrible, because it doesn't even matter ...

All kinds of private information can be found with google, or without it, on github, or any other site you like ... the question seems to be whose responsibility is it to keep your information safe ??

Google, they provide tools for searching ?
Github, they index and serve obviously private files ?
<insert any project name> Developers, they don't do every little thing they can think of to keep your private stuff private ?

Absolutely not ... 

The only thing common to github, google and <insert project name> is *you*. The only person responsible for *your* private information is *you*. The only thing able to determine what constitutes private information is *you*.

No other entity, not google, not github, not <insert project name> developers, nobody but you can fix the problem in it's entirety ... by not doing stupid things.

**Comment by potherca** [comment]
This may be late in the game, but what if I *want* my coverage to be found? Being able to put the generated Coverage HTML online for all to see might actually be something I _want_.

Not everybody likes jumping through hoops to get Coveralls/CodeCov/etc. working.

That makes two separate and conflicting scenarios to consider... sounds like more than just 5 lines of code to me.

**Comment by dbr-foodpanda** [comment]
Well you can still put it online, but do you want it to be indexed by a search engine? I think not even open source-projects want that. They rather want their api- or reference-docs to be listed, but not the (latest) coverage report, or?

**Comment by potherca** [comment]
Well, if anyone would _want_ to, a change like this would make it impossible, unless things were made to be configurable, which would mean more work, more logic, more possible bugs and more maintenance.

Placing the responsibility with the user means the user is free to choose _without a single line of code being changed_. Seems like a win to me...
