### ISSUE TITLE
Impossible to reach 100% coverage?

### ISSUE THREAD

**Issue by Ooypunk** [sebastianbergmann/php-code-coverage#513]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.7
| PHP version               | 5.6.25
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 5.7.17

So I have this class:
```PHP
<?php

class Main extends CI_Controller {

	/**
	 * Default controller/action.
	 * Redirect to login if not logged in yet.
	 */
	public function index() {
		if (!$this->auth->isLoggedIn()) {
			redirect(base_url('auth/login'));
		}
		redirect(base_url('employee'));
	}

}
```

With PHPUnit I test this controller/action, and after lines 10, 11 and 13 are marked as Executed. Now, because only 3 of 5 lines are marked executed, code coverage sticks at 60%, while I think it should be 100%. Is this normal behaviour?

**Comment by sebastianbergmann** [comment]
Please try with up-to-date versions of PHPUnit, php-code-coverage, and (most importantly) Xdebug.

**Comment by Ooypunk** [comment]
I wasn't aware I was so much behind!
Updated PHP, XDebug and PHPUnit (updated first post), but the output remains exactly the same.

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.
