### ISSUE TITLE
Code coverage is not generated when E_STRICT warnings are produced

### ISSUE THREAD

**Issue by joshuaspence** [sebastianbergmann/php-code-coverage#528]
It seems that code coverage is not generated if the source code produces `E_STRICT` warnings. I have produced a minimal reproduction case in [joshuaspence/phpunit-test](https://github.com/joshuaspence/phpunit-test).

```
> vendor/bin/phpunit --coverage-xml coverage.xml test/SomeTest.php
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

Declaration of SomeClass::someMethod($x) should be compatible with SomeOtherClass::someMethod()

> ls
composer.json  composer.lock  phpunit.xml  src  test  vendor
```

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
