### ISSUE TITLE
Coverage: accolades and brackets not covered

### ISSUE THREAD

**Issue by stephanvierkant** [sebastianbergmann/php-code-coverage#534]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version               | 7.1.5
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.4
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.2.1

As of phpunit 6.2, lines with only accolades, brackets or semicolons are not marked as covered. Problem didn't occur on 6.1 and 6.0.

![Screenshot PhpStorm](http://i.imgur.com/vXG7kKf.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
