### ISSUE TITLE
[FIXED in 6.2.4] HTML Code coverage highlighter broken

### ISSUE THREAD

**Issue by illusive-man** [sebastianbergmann/php-code-coverage#541]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version               | 7.1.4
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.2.2 - 6.2.3

Code Coverage highlighting wrong or not all lines. Looks like highlighting is shifted downwards one line. Plus lines 39, 48 aren't highlighted at all. (FYI code coverage for this class is 100%).

See the screenshot. 

![2017-07-06_2-16-43](https://user-images.githubusercontent.com/25516639/27888884-4bec3f10-61f1-11e7-8f93-a0e8c1f190eb.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by illusive-man** [comment]
Before sending all the required info, I'd like to ensure we're on the same page. 

Don't get me wrong but I wasn't  asking for the reason (literally), I'm telling that it's obviously a bug, because some time ago (a month maybe) everything was working fine with the same exact code.  I just noticed the difference and posted it here.  Sorry, I didn't mention that in the first post.

**Comment by sebastianbergmann** [comment]
Please provide the exact versions with which it worked and with which it does not work.

**Comment by illusive-man** [comment]
Sorry for not replying back for some time but after updating to 6.2.4 tonight everything is highlighted perfectly now! Except maybe, on rare occasion, highlighting includes closing curly brace. But that's Ok with me.  Thank you very much, Mr. Bergmann! We can close the ticket I suppose.
