### ISSUE TITLE
Code coverage erroneously marks lines as covered when using nesting loops / if statements

### ISSUE THREAD

**Issue by pr0nbaer** [sebastianbergmann/php-code-coverage#557]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.2
| PHP version               |  7.1.9
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.3
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.4.3

Given:
```php
final class Test
{

    function test()
    {
        foreach (range(0, 10) as $a) {
            foreach ([] as $b) {
                echo "This is green :(";
            }
        }

        foreach (range(0, 10) as $a) {
            foreach ([] as $b) {
                echo "BLAH";
                echo "BLAH";
                echo "BLAH";
                echo "This is green :(";
            }
        }

        foreach (range(0, 10) as $a) {
            if (false) {
                foreach (range(0, 10) as $b) {
                    echo "BLAH";
                    echo "BLAH";
                    echo "BLAH";
                    echo "This is green :(";
                }
            }
        }

        foreach (range(0, 10) as $a) {
            if (false) {
                foreach (range(0, 10) as $b) {
                    echo "This is green :(";
                }
            }
        }
    }

}
```
```php
class TestTest extends TestCase
{

    function test_it()
    {
        $t = new Test();

        $t->test();

        $this->assertTrue(true);
    }

}
```

When:

Running phpunit with `--coverage-html <dir>`

Expectation:

Lines with `echo "This is green :(";` should be red (not covered).

Reality:

Lines are green (covered).

**Comment by pr0nbaer** [comment]
Seems like Xdebug itself is reporting the wrong data.

```php
xdebug_start_code_coverage(XDEBUG_CC_UNUSED | XDEBUG_CC_DEAD_CODE);

// Content of Test::test() above

print_r(xdebug_get_code_coverage());
xdebug_stop_code_coverage();
```

will mark the wrong lines as executed, just like in the coverage report.

**Comment by pr0nbaer** [comment]
Seems like `phpdbg -qrr vendor/bin/phpunit ...` leads to the same result..

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

CC: @derickr

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by derickr** [comment]
For reference, this is the same issue as #589, #600, and #657.
