### ISSUE TITLE
Different coverage reports on local dev machine and Travis

### ISSUE THREAD

**Issue by antonioribeiro** [sebastianbergmann/php-code-coverage#566]
| Q                   | Travis | Local
| --------------------| ---------------|------
| PHPUnit version     | 6.4.4| 6.4.4
| PHP version         | 7.1.12| 7.1.8
| Installation Method | Composer / PHAR| Composer / PHAR

As per the images below, of course `PragmaRX\Version\Package\Console\Commands\Refresh` was not being tested, but why I'm getting a 100% coverage in my local dev machine?

### Development host

![image](https://user-images.githubusercontent.com/3182864/33406312-5b1d6722-d553-11e7-924b-ee7e2ac3a1f4.png)

### Travis

![image](https://user-images.githubusercontent.com/3182864/33406344-7ce22820-d553-11e7-88dc-e5895c4f0ab4.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
