### ISSUE TITLE
PhpUnit 6.4 CodeCoverage issue for Exception marking

### ISSUE THREAD

**Issue by KestutisIT** [sebastianbergmann/php-code-coverage#567]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | ?.?.?
| PHP version         | 7.1.10
| WP Version         | 4.9-RC1-42049-src
| Driver                    | Xdebug
| Installation Method | PhpUnit 2017.2.4 (Run Configuration) / PHAR PATH
| Usage Method              | PHPUnit / other
| Xdebug version (if used)  | 2.5.4
| PHPUnit version (if used)     | 6.4.3

Code Coverage does not mark as 'Green' the covered exception. While the test log says it passed the test - that means it got request exception of setting disallowed variable. But that is not shown in code coverage.

![phpunit 6 4 3 codecoverage issue for exception - 1](https://user-images.githubusercontent.com/4975202/32473006-092756b8-c36e-11e7-8fbf-521f89a66602.jpg)
![phpunit 6 4 3 codecoverage issue for exception - 2](https://user-images.githubusercontent.com/4975202/32473007-094dc12c-c36e-11e7-8bf5-d897a811c814.jpg)

PageView.php code sample:
```
<?php
namespace SampleMVC\Views;
use SampleMVC\Models\Language\LanguageInterface;

final class PageView
{
    private $vars = array();
    private $debugMode = 0;

    public function __get($name)
    {
        return $this->vars[$name];
    }

    public function __set($name, $value)
    {
        if($name == 'templateFile')
        {
            if(isset($this->vars['lang']) && $this->vars['lang'] instanceof LanguageInterface)
            {
                $objLang = $this->vars['lang'];
                $exceptionText = $objLang->getText('NS_TEMPLATE_CANNOT_BIND_VARIABLE_ERROR_TEXT');
            } else
            {
                $exceptionText = 'Cannot bind variable named &#39;templateFile&#39;';
            }
            // NOTE: We do not translate the system messages
            throw new \Exception($exceptionText);
        }
        $this->vars[$name] = $value;
    }
}
```

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
A screenshot of code coverage being displayed in PhpStorm is not helpful. I need a screenshot of the HTML code coverage report, for instance.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
