### ISSUE TITLE
Line not covered if function has leading backslash

### ISSUE THREAD

**Issue by kubawerlos** [sebastianbergmann/php-code-coverage#569]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.1.12
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.4

![coverage](https://user-images.githubusercontent.com/9282069/33810944-3f3e8182-de0c-11e7-94c3-2b5dba1facd5.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
Looks like an Xdebug issue to me. @derickr?

**Comment by derickr** [comment]
Happy to check, but I'm not going to re-type code from a screenshot. @kubawerlos, please provide the code itself.

**Comment by kubawerlos** [comment]
@derickr here you go:
```php
class Foo
{
    public function sort($array)
    {
        usort(
            $array,
            function ($x, $y) { return true; }
        );

        \usort(
            $array,
            function ($x, $y) { return true; }
        );

        return $array;
    }
}
```

@sebastianbergmann yes, it is fine when using phpdbg.

**Comment by derickr** [comment]
https://bugs.xdebug.org/view.php?id=1502 & https://github.com/xdebug/xdebug/pull/391
