### ISSUE TITLE
Coverage for one-liner in mixed HTML/PHP not shown

### ISSUE THREAD

**Issue by pretzlaw** [sebastianbergmann/php-code-coverage#616]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.2
| PHP version               | 7.0.26
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.8

When some class does:

```
unset( $_SESSION['login'] );
require_once 'template.php';
```

... no matter how strange this is...
then I expect such template.php code

```
<?php if ( ! isset( $_SESSION['login'] ) && ! is_user_logged_in() ): ?>

	Login now <?php echo '!'; ?>

<?php endif; ?>
```

to have coverage marked as green
but actually it does not adhere to one-liner (like the IF) :/ 

![grafik](https://user-images.githubusercontent.com/24290366/39767889-138b5136-52e8-11e8-8c9c-b64311f667a7.png)

But multiline PHP is shown as covered.

- Is this a thing of this package?
- Is this a problem in XDebug?

I really like to check if I covered every part of a template too.

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by pretzlaw** [comment]
Meanwhile I found out that this structure wont show any coverage:

```php
<?php if( $foo ): ?>

    html too low

<?php else: ?>
    Just right but if it has <?php echo 'php in same line'; ?>,
    then it wont show up in coverage either.

<?php endif; ?>
```

So I keep this in the back of my head:

- HTML must follow an inline PHP / No empty line allowed after inline PHP.
- HTML below inline PHP must not have another inline PHP.
- Empty line above inline PHP is okay and keeps the code readable (like before each endif or before each else).

With such rules the coverage is shown for the first line (at least):
 
![20180508-18 54 57-015](https://user-images.githubusercontent.com/24290366/39771243-b343fe04-52f1-11e8-9e19-0ad300a2c2fe.jpg)

Enough to see what part is rendered and what not.

So either document that or do you want to continue the issue?

**Comment by CJDennis** [comment]
@pretzlaw I think sebastian also wants the `php -v` output and a small archive of working code that reproduces the problem.

**Comment by CJDennis** [comment]
@sebastianbergmann Please find an example at https://github.com/CJDennis/html-coverage.

You'll note when you run the unit test with coverage that no lines with PHP tags get covered, despite some of them having executable code as well.
