### ISSUE TITLE
Not getting coverage inside elseif () clause

### ISSUE THREAD

**Issue by tarlepp** [sebastianbergmann/php-code-coverage#620]
| Q                         | A
| --------------------------| ---------------
| PHP version               | 7.2.5-0ubuntu0.18.04.1 (cli)
| Driver                    | Xdebug 
| Xdebug version (if used)  | v2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 7.1.5

![image](https://user-images.githubusercontent.com/595561/40322637-a72b4830-5d3b-11e8-88cc-f19d279fab1c.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

CC @derickr

**Comment by tarlepp** [comment]
What I'm not understanding why is line 66 hit but line 62 which leads to that point isn't. I'll create simple repo to point this out.

**Comment by tarlepp** [comment]
I created this repository to show this issue https://github.com/tarlepp/phpunit-coverage-poc2

**Comment by derickr** [comment]
Hi,

I can actually reproduce this, but from what I see, this is not something that Xdebug does wrong. From my smaller tests (you really don't need all of phpunit and tests for this, just PHP Code Coverage), Xdebug provides the right output.

cheers,
Derick

**Comment by sebastianbergmann** [comment]
@derickr Can you provide a minimal example along with raw data from Xdebug and what php-code-coverage generates from that? Thanks!
