### ISSUE TITLE
Version 9.0.0 "use" Trait not longer covered

### ISSUE THREAD

**Issue by Neunerlei** [sebastianbergmann/php-code-coverage#790]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.0.0
| PHP version               | 7.3.17
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.9.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.3.3

Hello there. 
After updating from phpunit 9.2.5 to 9.3.3 all "use trait" statements in classes are marked as "uncovered" (See screenshots below). I updated the phpunit.xml using the cli migration option but could not see any changes. Did I miss something in the changelog? 

With version code-coverage: 8.0.2 and phpunit: 9.2.5:
![image](https://user-images.githubusercontent.com/22350956/89737128-ffbc2700-da6e-11ea-8b63-b64399efece1.png)

phpunit.xml: 
```
<phpunit colors="true" bootstrap="vendor/autoload.php">
    <testsuites>
        <testsuite name="Unit Tests">
            <directory>./Tests/Unit/</directory>
        </testsuite>
        <testsuite name="Functional Tests">
            <directory>./Tests/Functional/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./Classes/</directory>
        </whitelist>
    </filter>
</phpunit>
```

After code-coverage: 9.0.0 and phpunit: 9.3.3:
![image](https://user-images.githubusercontent.com/22350956/89737227-bb7d5680-da6f-11ea-951d-a192b8fe842f.png)

phpunit.xml:
```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" colors="true" bootstrap="vendor/autoload.php" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd">
  <coverage processUncoveredFiles="true">
    <include>
      <directory suffix=".php">./Classes/</directory>
    </include>
  </coverage>
  <testsuites>
    <testsuite name="Unit Tests">
      <directory>./Tests/Unit/</directory>
    </testsuite>
    <testsuite name="Functional Tests">
      <directory>./Tests/Functional/</directory>
    </testsuite>
  </testsuites>
</phpunit>
``` 

Thanks in advance!

**Comment by dvdoug** [comment]
Hi @Neunerlei

Thanks for the bug report. There appear to be 3 things going on here that combine to give the effect you're seeing😞

1) Xdebug is reporting the `use` statement as an executable line under PHP7.3. I can only reproduce this under PHP7.3, on PHP7.4 the line is correctly reported as non-executable. Please can you file an Xdebug bug over at https://bugs.xdebug.org ?
2) https://bugs.xdebug.org/view.php?id=1798 then appears to be involved. As a workaround, if you set `processUncoveredFiles ="false"`, I'm 99% sure that you'll see the line appear as covered instead.
3) The reason this wasn't visible before is that php-code-coverage v9 trusts the driver more than earlier versions to determine whether a line is executable or not rather than having custom logic.

@sebastianbergmann this _could_ be worked around by adding T_USE to the list of affected tokens at https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/ParsingCoveredFileAnalyser.php#L207, but unlike the existing set, this one would have side effects as it would negatively affect code constructs like the below

```php
$foo = array_filter($foo, function (Bar $bar) use ($x, $y, $z) {
    //something
});
```

Does PHP-Parser distinguish between the two different types of `use`?

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann this _could_ be worked around by adding T_USE to the list of affected tokens

I would like to avoid workarounds for bugs in Xdebug or PCOV.

**Comment by Neunerlei** [comment]
> Hi @Neunerlei
> 
> Thanks for the bug report. There appear to be 3 things going on here that combine to give the effect you're seeing😞
> 
> 1. Xdebug is reporting the `use` statement as an executable line under PHP7.3. I can only reproduce this under PHP7.3, on PHP7.4 the line is correctly reported as non-executable. Please can you file an Xdebug bug over at https://bugs.xdebug.org ?

Hi there,

thanks for your response @dvdoug! I can confirm, it works fine for PHP 7.4. 
I migrated my dev environment to the newer version and get 100% code coverage again 👍 

I also created an issue for xdebug, for cross refrence: https://bugs.xdebug.org/view.php?id=1830

Thank you both for your help and work on this project!
