### ISSUE TITLE
Use the same default columns order for files or directory report

### ISSUE THREAD

**Issue by thg2k** [sebastianbergmann/php-code-coverage#827]
Greetings,

I find it a bit confusing while jumping between directory and file reports that the columns are ordered in the opposite way. It would be greatly appreciate (and I believe a nice improvement) if the order were the same. Currently:

Directory report: Lines / Functions and Methods / Classes and Traits
File report: Classes and Traits / Functions and Methods / Lines

Either one would be fine, just please use the same one so the brain can get used to where to look for what information.

**Comment by CJDennis** [comment]
I would prefer the order [ Lines | Functions and Methods | Classes and Traits ] because then the blank column is not next to the method names in the file reports. It also makes more sense to me if the first column can be highlighted in all three colours instead of just red or green.

  | Lines | Functions and Methods | Classes and Traits
--- | --- | --- | ---
Total | 95% | 50% | 0%
MyClass | 95% | 50% | 0%
__construct | 100% | 100% | 
my_method | 90% | 0% |
