### ISSUE TITLE
Trait path coverage lists coverage on the trait itself

### ISSUE THREAD

**Issue by jonnybarnes** [sebastianbergmann/php-code-coverage#841]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.5
| PHP version               | 8.0.0
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.0.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.0

Path and branch inspection seems to claim traits are themselves uncovered.

Classes which use my `FilterHtml` trait have the imported methods marked as “covered” in the class. However, the `FilterHtml` trait itself is being marked as an uncovered path.

If I add the `@codeCoverageIgnore` annotation I lose all code coverage analysis.

I tried adding a test using `getMockForTrait` but that just adds another entry to the path list, and leaves the actual trait listed as uncovered. So I’m not sure what the best way of setting this up is.

![Screen Shot 2020-12-30 at 20 12 23-fullpage](https://user-images.githubusercontent.com/108303/103378765-605e0600-4adb-11eb-9c01-cdc4134b1d89.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by jonnybarnes** [comment]
Hi @sebastianbergmann 

I’ve added a repo here with the simplest failing case I can think: https://github.com/jonnybarnes/trait-path-coverage

There’s one class, one trait, and one test case

**Comment by dvdoug** [comment]
Hi @jonnybarnes 

Thanks for the reduced testcase, having a sample to reproduce with helps a lot.

With this one, it looks to me like the issue is with Xdebug rather than php-code-coverage - the report output in your screenshots is because the line based and branch/path based coverage has a disagreement in the raw data.

You can report Xdebug issues over at https://bugs.xdebug.org


```
C:\tmp\trait-path-coverage\src\Bar.php = {array} [2]
 lines = {array} [4]
  7 = {int} 1
  13 = {int} 1
  14 = {int} -2
  16 = {int} 1
 functions = {array} [2]
  App\Bar->useTrait = {array} [2]
   branches = {array} [1]
    0 = {array} [7]
     op_start = {int} 0
     op_end = {int} 8
     line_start = {int} 11
     line_end = {int} 14
     hit = {int} 1
     out = {array} [0]
     out_hit = {array} [0]
   paths = {array} [1]
  {main} = {array} [2]
   branches = {array} [1]
    0 = {array} [7]
     op_start = {int} 0
     op_end = {int} 3
     line_start = {int} 3
     line_end = {int} 16
     hit = {int} 1
     out = {array} [1]
     out_hit = {array} [1]
   paths = {array} [1]
C:\tmp\trait-path-coverage\src\FooTrait.php = {array} [2]
 lines = {array} [3]
  11 = {int} 1   <------------------------------------------- this says the line was executed
  12 = {int} -2
  14 = {int} 1
 functions = {array} [2]
  App\FooTrait->returnsTrue = {array} [2]
   branches = {array} [1]
    0 = {array} [7]
     op_start = {int} 0
     op_end = {int} 5
     line_start = {int} 9
     line_end = {int} 12
     hit = {int} 0    <----------------------------------------- this says the branch was not
     out = {array} [0]
     out_hit = {array} [0]
   paths = {array} [1]
  {main} = {array} [2]
   branches = {array} [1]
    0 = {array} [7]
     op_start = {int} 0
     op_end = {int} 2
     line_start = {int} 3
     line_end = {int} 14
     hit = {int} 1
     out = {array} [1]
     out_hit = {array} [1]
   paths = {array} [1]
```

**Comment by jonnybarnes** [comment]
Thanks for the feedback, have raised a bug report upstream here: https://bugs.xdebug.org/view.php?id=1938
