### ISSUE TITLE
Coverage PHP 8 constructor property promotion not covered

### ISSUE THREAD

**Issue by frankvanhest** [sebastianbergmann/php-code-coverage#843]
When running phpunit 9.5 with --coverage-html or --coverage-text in PHP 8, a constructor with property promotion is marked as not covered as shown in the image below.

![Screenshot 2021-01-14 at 10 52 49](https://user-images.githubusercontent.com/2206481/104574726-a6c47080-5656-11eb-8707-542b964e2cd6.png)

But when it is run with --coverage-clover using PhpStorm, the code is marked as covered.

![Screenshot 2021-01-14 at 10 54 08](https://user-images.githubusercontent.com/2206481/104574881-d5dae200-5656-11eb-9b68-696cacbca909.png)

Am I missing something configuration wise?
If you need information I'll be happy to provide it.

[Update]
Used versions:
- PHP: 8.0.0
- PHP Code Coverage: 9.2.5
- Xdebug: 3.0.1
- PHPUnit: 9.5.0

Output `php -v`:
```
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
```

Tar archive to reproduce the case: 
[issue.tar.gz](https://github.com/sebastianbergmann/php-code-coverage/files/5813799/issue.tar.gz)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
CC @derickr

**Comment by frankvanhest** [comment]
@sebastianbergmann, my apologies for the missing information. I've updated the description with the information needed below `[Update]`

**Comment by sebastianbergmann** [comment]
Xdebug 3.0.2 has the fix you need: https://bugs.xdebug.org/bug_view_page.php?bug_id=00001910

**Comment by frankvanhest** [comment]
Thank you for the quick response!
