### ISSUE TITLE
Wrong results with PHPUnit

### ISSUE THREAD

**Issue by daycry** [sebastianbergmann/php-code-coverage#871]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.7
| PHP version               | 7.4.13
| Driver                    | Xdebug / PHPDBG
| Xdebug version (if used)  | 3.0.4
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | 9.5.10

I don't know if it's an error or what happens, but PHPUnit returns strange results

![image](https://user-images.githubusercontent.com/7590335/135464514-12eb5e10-2b6a-49e5-b857-d75dfc8c3789.png)

![image](https://user-images.githubusercontent.com/7590335/135464606-90dc53b0-3f15-4b4b-adef-99b227a29407.png)

I do not understand why it marks it as not executed, when it is not true.

Can you help me?

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by mikkorantalainen** [comment]
Also, if you get all the other lines green but one line guarded by if-statement is red, the changes are high that your test case does not actually test that branch. Are you use you have a working test for the invalid network configuration, too?

**Comment by sebastianbergmann** [comment]
No feedback, closing.
