### ISSUE TITLE
Document return type of CodeUnitFindingVisitor::enterNode() so that Symfony's DebugClassLoader does not trigger a deprecation warning

### ISSUE THREAD

**Issue by tft7000** [sebastianbergmann/php-code-coverage#887]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.9
| PHP version               | 8.0.13 / 8.1.0
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.1.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.10

Since Symfony 5.4 release PHPUnit ends with exit code 1 if I start it with code coverage:

```bash
XDEBUG_MODE=coverage symfony php vendor/bin/simple-phpunit --coverage-text
```

the above command ends with the message:
```
Remaining indirect deprecation notices (1)

  1x: Method "PhpParser\NodeVisitor::enterNode()" might add "int|Node|null" as a native return type declaration in the future. Do the same in implementation "SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in CodeCoverage::stop from SebastianBergmann\CodeCoverage

exit status 1
```

I believe this has the same reason as here: https://github.com/sebastianbergmann/php-file-iterator/pull/74 (Document return type of Iterator::accept() so that Symfony's DebugClassLoader does not trigger a deprecation warning)

If I manually set a `@return int|Node|null` php doc comment for `\SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor::enterNode` phpunit will end without error.

Also if I add `"symfony/error-handler": "<5.4"` as require-dev dependency in composer.json, I do not experience an error.
This seems to be the only workaround I can do as end-user.

Suggested fix:
add correct return type php doc comment for the `enterNode` method. I assume it is `null` (is void and null the same?)

**Comment by ostrolucky** [comment]
Also see https://github.com/doctrine/DoctrineBundle/runs/4419682004?check_suite_focus=true to see error in action

**Comment by sebastianbergmann** [comment]
In https://github.com/sebastianbergmann/php-file-iterator/pull/74, which you reference, the `#[\ReturnTypeWillChange]` attribute was involved and therefore the changed proposed there made sense to me. I think that the situation here is different.

`PhpParser\NodeVisitor` has

```php
/**
 * @return null|int|Node Replacement node (or special return value)
 */
public function enterNode(Node $node);
```

and `PhpParser\NodeVisitorAbstract` (which implements `PhpParser\NodeVisitor`)

has

```php
public function enterNode(Node $node) {
    return null;
}
```

`SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor` (which extends `PhpParser\NodeVisitorAbstract`) has

```php
public function enterNode(Node $node)
{
}
```

which matches `PhpParser\NodeVisitorAbstract::enterNode()`.

There is no `#[\ReturnTypeWillChange]` attribute in the code of either `PhpParser\NodeVisitor` or `PhpParser\NodeVisitorAbstract`. So why does Symfony's DebugClassLoader assume that `Method "PhpParser\NodeVisitor::enterNode()" might add "int|Node|null" as a native return type declaration in the future`? I assume that if @nikic had plans to change this return type that he would have added the `#[\ReturnTypeWillChange]` attribute to document this intent.

The concept of Symfony's DebugClassLoader seems to be well-intentioned, but I believe it to be flawed. It complains about code that it is not responsible for, it uses dynamic testing instead of static analysis, and because this dynamic testing is performed as part of running a test suite using PHPUnit there is a potential of people thinking that this output comes from PHPUnit.

**Comment by tft7000** [comment]
@sebastianbergmann : Thank you very much for the fix and sorry for the inconvenience it caused you. The coverage test is now working as expected.
