### ISSUE TITLE
AssertionError exception missing NullableType

### ISSUE THREAD

**Issue by sfmok** [sebastianbergmann/php-code-coverage#944]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.17
| PHP version               | 8.0.17
| Driver                    | PCOV
| PCOV version    | 1.0.11
| Xdebug version  | No
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.25

I did an upgrade of PHP to 8.0 and PHPUnit 9.5 afterwards my test was down and got this error:
`assert($type instanceof Identifier || $type instanceof Name || $type instanceof ComplexType)`

After some debugging, I found the issue related to `php-code-coverage` associated with this commit: https://github.com/sebastianbergmann/php-code-coverage/commit/12856cc6e3827ed187c588fff59baa011bab328d where the `NullableType` has been removed from assert condition

**Comment by sebastianbergmann** [comment]
I do not understand how this would happen as `PhpParser\Node\NullablyType` extends `PhpParser\Node\ComplexType`.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by vitormattos** [comment]
This is related of https://github.com/sebastianbergmann/php-code-coverage/issues/878

Look this commit:

https://github.com/nikic/PHP-Parser/commit/0483391aca4c9f0acaf8b48cd51945fbc7fa172a#diff-9a94020b5be1fe2fc31b76831df579eff4d1bd66e3141477dda04972d5241b8e

The parent class was changed from `NodeAbstract` to `ComplexType since version v4.13.0 of php-parser.

If got this terror is because is using in a project that is loading an old version of php-parser.
